### ISSUE TITLE
Template screens and logo

### ISSUE THREAD

**Issue by Delphine002** [zuri-training/my_cms--Team-Crow#6]
Design the 3 teplate category screens and brand logo

**Comment by makolly** [comment]
Please can you do a quick review of the logo I designed and see if I have to make corrections:
https://www.figma.com/file/IVtnnkZt9tdjK40cHZgAYA/My-CMS_-Zuri?node-id=447%3A1668&t=MoBiA3398WBOKrBu-3

**Comment by Delphine002** [comment]
You will have to redesign the logo without the bird in it. Good job tho

**Comment by Delphine002** [comment]
Good job

**Comment by makolly** [comment]
Thank you very much Team Lead
